### ISSUE TITLE
UI.openpanel returns no slashes

### ISSUE THREAD

**Issue by cloo** [alexschreyer/Ruby-Code-Editor-for-SketchUp#21]
UI.openpanel("Choose any file from the folder", "/", "*")`
returns the path stripped of slashes:
C:UsersMeDesktopimage.jpg

Using the code in Ruby Console works as expected.

Windows 10 
Sketchup 2017 Make

**Comment by cloo** [comment]
There is a workaround to replace backslashes with forward ones before output:
`imglocation = UI.openpanel("Choose", "/", "*").gsub!(/\\/, '/')`
[The discussion suggests](https://forums.sketchup.com/t/ui-openpanel-returns-no-slashes/66466/2), that Ruby Code Editor probably just doesnt' escape backslashes before output.

**Comment by alexschreyer** [comment]
Try this:
```
imglocation = UI.openpanel("Choose any file from the folder", "/", "*")
UI.messagebox imglocation
```
The result is consistent with the Ruby Console and therefore the variable has the path in it. It's just the results-box at the bottom that somehow strips the slashes. Have to find out why that is.

**Comment by cloo** [comment]
Cool, I'm glad the code works anyway!
